<?php

namespace UserBundle\Repository;

/**
 * UserActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserActionRepository extends \Doctrine\ORM\EntityRepository
{
}
