<?php

namespace ConfigBundle\Repository;

/**
 * ConfParametrageCompteComptableOrdinaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfParametrageCompteComptableOrdinaireRepository extends \Doctrine\ORM\EntityRepository
{
}
