<?php

namespace ConfigBundle\Repository;

/**
 * ConfTypeCompteComptableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfTypeCompteComptableRepository extends \Doctrine\ORM\EntityRepository
{
}
