<?php

namespace ConfigBundle\Repository;

/**
 * ConfParametrageContrepartieDepositaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfParametrageContrepartieDepositaireRepository extends \Doctrine\ORM\EntityRepository
{
}
