<?php

namespace ConfigBundle\Repository;

/**
 * ConfJournalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfJournalRepository extends \Doctrine\ORM\EntityRepository
{
}
