<?php

namespace ConfigBundle\Repository;

/**
 * ConfDetailModeleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfDetailModeleRepository extends \Doctrine\ORM\EntityRepository
{
}
