<?php

namespace ConfigBundle\Repository;

/**
 * ConfTypeOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfTypeOperationRepository extends \Doctrine\ORM\EntityRepository
{
}
