<?php

namespace ConfigBundle\Repository;

/**
 * ConfAgenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfAgenceRepository extends \Doctrine\ORM\EntityRepository
{
}
