<?php

namespace ConfigBundle\Repository;

/**
 * ConfNatureOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfNatureOperationRepository extends \Doctrine\ORM\EntityRepository
{
}
