<?php

namespace ConfigBundle\Repository;

/**
 * ConfParametrageCompteComptableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfParametrageCompteComptableRepository extends \Doctrine\ORM\EntityRepository
{
}
