<?php

namespace ConfigBundle\Repository;

/**
 * ConfTypeAnalytiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfTypeAnalytiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
