<?php

namespace ConfigBundle\Repository;

/**
 * ConfCategorieBilanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfCategorieBilanRepository extends \Doctrine\ORM\EntityRepository
{
}
