<?php

namespace ConfigBundle\Repository;

/**
 * ConfPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
