<?php

namespace ConfigBundle\Repository;

/**
 * ConfTauxFiscalAppliqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfTauxFiscalAppliqueRepository extends \Doctrine\ORM\EntityRepository
{
}
