<?php

namespace ConfigBundle\Repository;

/**
 * ConfFormuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfFormuleRepository extends \Doctrine\ORM\EntityRepository
{
}
