<?php

namespace ConfigBundle\Repository;

/**
 * ConfSchemaOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfSchemaOperationRepository extends \Doctrine\ORM\EntityRepository
{
}
