<?php

namespace ConfigBundle\Repository;

/**
 * ConfExerciceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfExerciceRepository extends \Doctrine\ORM\EntityRepository
{
}
