<?php

namespace ConfigBundle\Repository;

/**
 * ConfCompteComptablePlanDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfCompteComptablePlanDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
