<?php

namespace ConfigBundle\Repository;

/**
 * ConfTypeTiersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfTypeTiersRepository extends \Doctrine\ORM\EntityRepository
{
}
