<?php

namespace ConfigBundle\Repository;

/**
 * ConfFiscRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfFiscRepository extends \Doctrine\ORM\EntityRepository
{
}
