<?php

namespace ConfigBundle\Repository;

/**
 * ConfParametrageCompteComptableTitreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfParametrageCompteComptableTitreRepository extends \Doctrine\ORM\EntityRepository
{
}
