<?php

namespace ConfigBundle\Repository;

/**
 * ConfNatureOperationDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfNatureOperationDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
