<?php

namespace ConfigBundle\Repository;

/**
 * ConfIbRubriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfIbRubriqueRepository extends \Doctrine\ORM\EntityRepository
{
}
