<?php

namespace ConfigBundle\Repository;

/**
 * ConfTiersSchemaOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfTiersSchemaOperationRepository extends \Doctrine\ORM\EntityRepository
{
}
