<?php

namespace ConfigBundle\Repository;

/**
 * ConfFormuleNatureOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfFormuleNatureOperationRepository extends \Doctrine\ORM\EntityRepository
{
}
