<?php

namespace ConfigBundle\Repository;

/**
 * ConfSocieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfSocieteRepository extends \Doctrine\ORM\EntityRepository
{
public function findSocieteByAjaxSearchAction($query) {
    $em = $this->getEntityManager();
    return $em->createQuery('
            SELECT s FROM ConfigBundle:ConfSociete s
            WHERE  s.supprimer = :sup and s.codeSociete LIKE :query or s.sigle LIKE :query or s.description  LIKE :query')->setParameter('query', '%' . $query . '%')->setParameter('sup', FALSE)->setMaxResults(10)->getResult();

}

}
