<?php

namespace ConfigBundle\Repository;

/**
 * ConfIbApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfIbApplicationRepository extends \Doctrine\ORM\EntityRepository
{
}
