<?php

namespace ConfigBundle\Repository;

/**
 * TypeCompteComptableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCompteComptableRepository extends \Doctrine\ORM\EntityRepository
{
}
