<?php

namespace MetierBundle\Repository;

/**
 * MetierMouvementTitreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetierMouvementTitreRepository extends \Doctrine\ORM\EntityRepository
{
}
