<?php

namespace MetierBundle\Repository;

/**
 * MetierExtourneOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetierExtourneOperationRepository extends \Doctrine\ORM\EntityRepository
{
}
