<?php

namespace MetierBundle\Repository;

/**
 * MetierVerificationOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetierVerificationOperationRepository extends \Doctrine\ORM\EntityRepository
{
}
