<?php

namespace MetierBundle\Repository;

/**
 * MetierMouvementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetierMouvementRepository extends \Doctrine\ORM\EntityRepository
{
}
