<?php

namespace MetierBundle\Repository;

/**
 * MetierValeurIbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetierValeurIbRepository extends \Doctrine\ORM\EntityRepository
{
}
