<?php

namespace MetierBundle\Repository;

/**
 * MetierMouvementOrdinaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetierMouvementOrdinaireRepository extends \Doctrine\ORM\EntityRepository
{
}
