<?php

namespace MetierBundle\Repository;

/**
 * MetierTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetierTransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
