<?php

namespace MetierBundle\Repository;

/**
 * MetierDetailsOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetierDetailsOperationRepository extends \Doctrine\ORM\EntityRepository
{
}
