<?php

namespace MetierBundle\Repository;

/**
 * MetierValeurFormuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetierValeurFormuleRepository extends \Doctrine\ORM\EntityRepository
{
}
