<?php

namespace MetierBundle\Repository;

/**
 * MetierTiersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetierTiersRepository extends \Doctrine\ORM\EntityRepository
{
}
